### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [AdhamAwadhi/Cake.ConventionalChangelog#3]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by gep13** [comment]
@AdhamAwadhi I just wanted to follow up to see if you had given any thought to this issue.  Thanks

**Comment by gep13** [comment]
@AdhamAwadhi just wanted to touch base again about this issue.  What are your thoughts on it?  Thanks

**Comment by AdhamAwadhi** [comment]
Sorry for late reply, I was out for long time. 
I will update it and push to github and nuget

**Comment by gep13** [comment]
@AdhamAwadhi thanks for getting back to me, I appreciate it!  Thanks for getting this package updated!  The adding of the cake-contrib user to the NuGet package is something that is done through the NuGet.org website, and a request would be sent for one of the Cake Contrib team to accept.  Please let me know if you have any questions.

**Comment by AdhamAwadhi** [comment]
I added cake-contrib use on NuGet

**Comment by gep13** [comment]
@AdhamAwadhi I have just accepted the request for become a maintainer!  Thanks for taking the time to do this!
